#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/bootstrap/vendor_warning_filter.php';

$restoreVendorWarningFilter = registerOptionalVendorWarningFilter();

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

$restoreVendorWarningFilter();
unset($restoreVendorWarningFilter);

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
