<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // 1. Change the column type from enum (with old Portuguese values) to string
        //    so it accepts the new English values. This is required because SQLite
        //    enforces CHECK constraints generated by enum().
        Schema::table('standard_weights', function (Blueprint $table) {
            $table->string('status', 30)->default('active')->change();
        });

        // 2. StandardWeight status: Portuguese → English lowercase
        $map = [
            'ativo' => 'active',
            'em_calibracao' => 'in_calibration',
            'fora_de_uso' => 'out_of_service',
            'descartado' => 'discarded',
        ];

        foreach ($map as $old => $new) {
            DB::table('standard_weights')->where('status', $old)->update(['status' => $new]);
        }
    }

    public function down(): void
    {
        $map = [
            'active' => 'ativo',
            'in_calibration' => 'em_calibracao',
            'out_of_service' => 'fora_de_uso',
            'discarded' => 'descartado',
        ];

        foreach ($map as $old => $new) {
            DB::table('standard_weights')->where('status', $old)->update(['status' => $new]);
        }

        Schema::table('standard_weights', function (Blueprint $table) {
            $table->enum('status', ['ativo', 'em_calibracao', 'fora_de_uso', 'descartado'])->default('ativo')->change();
        });
    }
};
