export const queryKeys = {
  customers: {
    all: ['customers'] as const,
    list: (params: Record<string, unknown>) => ['customers', params] as const,
    detail: (id: number) => ['customers', id] as const,
    contacts: (id: number) => ['customers', id, 'contacts'] as const,
    options: ['customer-options'] as const,
    sellersOptions: ['sellers-options'] as const,
    customer360: (id: number) => ['customer-360', id] as const,
    duplicates: (searchType: string) => ['customer-duplicates', searchType] as const,
    documents: (id: number) => ['customer-documents', id] as const,
  },
  workOrders: {
    all: ['work-orders'] as const,
    list: (params: Record<string, unknown>) => ['work-orders', params] as const,
    detail: (id: number) => ['work-orders', id] as const,
    metadata: ['work-orders-metadata'] as const,
    dashboardStats: ['work-orders-dashboard-stats'] as const,
    techniciansOptions: ['technicians-options'] as const,
    checklist: (id: string) => ['wo-checklist', id] as const,
    checklistTemplate: (templateId: number | undefined) => ['wo-checklist-template', templateId] as const,
    costEstimate: (id: string) => ['wo-cost-estimate', id] as const,
    customerEquipments: (customerId: number) => ['customer-equipments', customerId] as const,
    partsKitsOptions: ['parts-kits-select'] as const,
    kanban: (search: string) => ['work-orders', 'kanban', search] as const,
  },
  quotes: {
    all: ['quotes'] as const,
    list: (params: Record<string, unknown>) => ['quotes', params] as const,
    detail: (id: number) => ['quotes', id] as const,
    summary: ['quotes-summary'] as const,
    advancedSummary: ['quotes-advanced-summary'] as const,
    kanban: ['quotes-kanban'] as const,
    tags: ['quote-tags'] as const,
    templates: ['quote-templates'] as const,
  },
  equipment: {
    all: ['equipments'] as const,
    list: (params: Record<string, unknown>) => ['equipments', params] as const,
    detail: (id: number) => ['equipments', id] as const,
    dashboard: ['equipments-dashboard'] as const,
    alerts: ['equipments-alerts'] as const,
    constants: ['equipments-constants'] as const,
    models: (params?: Record<string, unknown>) => ['equipment-models', params ?? {}] as const,
  },
  financial: {
    receivables: {
      all: ['accounts-receivable'] as const,
      list: (params: Record<string, unknown>) => ['accounts-receivable', params] as const,
      summary: ['accounts-receivable-summary'] as const,
    },
    payables: {
      all: ['accounts-payable'] as const,
      list: (params: Record<string, unknown>) => ['accounts-payable', params] as const,
      summary: ['accounts-payable-summary'] as const,
      categories: ['account-payable-categories'] as const,
    },
    expenses: {
      all: ['expenses'] as const,
      list: (params: Record<string, unknown>) => ['expenses', params] as const,
      summary: ['expense-summary'] as const,
      analytics: ['expense-analytics'] as const,
      categories: ['expense-categories'] as const,
    },
    chartOfAccounts: (params?: Record<string, unknown>) => ['chart-of-accounts', params ?? {}] as const,
    invoices: {
      all: ['invoices'] as const,
      list: (params: Record<string, unknown>) => ['invoices', params] as const,
    },
    payments: {
      all: ['payments'] as const,
      summary: ['payments-summary'] as const,
    },
    bankAccounts: {
      all: ['bank-accounts'] as const,
      list: (params: Record<string, unknown>) => ['bank-accounts', params] as const,
      options: ['bank-accounts-options'] as const,
    },
    paymentMethods: ['payment-methods'] as const,
    fundTransfers: {
      list: (params: Record<string, unknown>) => ['fund-transfers', params] as const,
      summary: ['fund-transfers-summary'] as const,
    },
    cashFlow: ['cash-flow'] as const,
    dre: (params: { from: string; to: string }) => ['financial-dre', params.from, params.to] as const,
    consolidated: ['financial-consolidated'] as const,
    agingReport: ['financial-aging-report'] as const,
    reconciliationRules: (params?: Record<string, unknown>) => ['reconciliation-rules', params ?? {}] as const,
    commissions: {
      events: (params: Record<string, unknown>) => ['commission-events', params] as const,
      settlements: ['commission-settlements'] as const,
      dashboard: ['commission-dashboard'] as const,
      rules: ['commission-rules'] as const,
    },
  },
  stock: {
    all: ['stock'] as const,
    movements: {
      all: ['stock-movements'] as const,
      list: (params: Record<string, unknown>) => ['stock-movements', params] as const,
    },
    warehouses: {
      all: ['warehouses'] as const,
      list: (params: Record<string, unknown>) => ['warehouses', params] as const,
    },
    batches: {
      all: ['batches'] as const,
      list: (params: Record<string, unknown>) => ['batches', params] as const,
    },
    inventories: ['inventories'] as const,
    transfers: ['stock-transfers'] as const,
    summary: ['stock-summary'] as const,
    lowAlerts: ['stock-low-alerts'] as const,
  },
  serviceCalls: {
    all: ['service-calls'] as const,
    list: (params: Record<string, unknown>) => ['service-calls', params] as const,
    detail: (id: number) => ['service-calls', id] as const,
    summary: ['service-calls-summary'] as const,
    kpi: ['service-calls-kpi'] as const,
    map: ['service-calls-map'] as const,
  },
  crm: {
    deals: {
      all: ['crm-deals'] as const,
      list: (params: Record<string, unknown>) => ['crm-deals', params] as const,
    },
    pipelines: ['crm-pipelines'] as const,
    activities: ['crm-activities'] as const,
    dashboard: ['crm-dashboard'] as const,
  },
  central: {
    items: {
      all: ['central-items'] as const,
      list: (params: Record<string, unknown>) => ['central-items', params] as const,
      detail: (id: number) => ['central-items', id] as const,
    },
    summary: ['central-summary'] as const,
    kpis: ['central-kpis'] as const,
  },
  users: {
    all: ['users'] as const,
    list: (params: Record<string, unknown>) => ['users', params] as const,
    detail: (id: number) => ['users', id] as const,
    options: ['users-select'] as const,
  },
  roles: {
    all: ['roles'] as const,
  },
  products: {
    all: ['products'] as const,
    list: (params: Record<string, unknown>) => ['products', params] as const,
    options: ['products-select'] as const,
  },
  services: {
    all: ['services'] as const,
    list: (params: Record<string, unknown>) => ['services', params] as const,
    options: ['services-select'] as const,
  },
  suppliers: {
    all: ['suppliers'] as const,
    list: (params: Record<string, unknown>) => ['suppliers', params] as const,
  },
  notifications: {
    all: ['notifications'] as const,
    unreadCount: ['notifications-unread-count'] as const,
  },
  dashboard: ['dashboard-stats'] as const,
  dashboardCache: ['dashboard'] as const,
  settings: ['settings'] as const,
  tenantSettings: ['tenant-settings'] as const,
  maintenanceReports: {
    all: ['maintenance-reports'] as const,
    list: (workOrderId: number) => ['maintenance-reports', { work_order_id: workOrderId }] as const,
    detail: (id: number) => ['maintenance-reports', id] as const,
  },
} as const
